# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messenger_pb2 as messenger__pb2


class MessengerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/MessengerService/Send',
        request_serializer=messenger__pb2.ChatMessage.SerializeToString,
        response_deserializer=messenger__pb2.Response.FromString,
        )
    self.Recieve = channel.unary_stream(
        '/MessengerService/Recieve',
        request_serializer=messenger__pb2.RecieveRequest.SerializeToString,
        response_deserializer=messenger__pb2.ChatMessage.FromString,
        )
    self.Login = channel.unary_unary(
        '/MessengerService/Login',
        request_serializer=messenger__pb2.LoginRequest.SerializeToString,
        response_deserializer=messenger__pb2.Response.FromString,
        )
    self.Logout = channel.unary_unary(
        '/MessengerService/Logout',
        request_serializer=messenger__pb2.LogoutRequest.SerializeToString,
        response_deserializer=messenger__pb2.Response.FromString,
        )


class MessengerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Recieve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Logout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessengerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=messenger__pb2.ChatMessage.FromString,
          response_serializer=messenger__pb2.Response.SerializeToString,
      ),
      'Recieve': grpc.unary_stream_rpc_method_handler(
          servicer.Recieve,
          request_deserializer=messenger__pb2.RecieveRequest.FromString,
          response_serializer=messenger__pb2.ChatMessage.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=messenger__pb2.LoginRequest.FromString,
          response_serializer=messenger__pb2.Response.SerializeToString,
      ),
      'Logout': grpc.unary_unary_rpc_method_handler(
          servicer.Logout,
          request_deserializer=messenger__pb2.LogoutRequest.FromString,
          response_serializer=messenger__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MessengerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
